services:
  db:
    container_name: filefly_db
    image: postgres:18.3-alpine
    environment:
      POSTGRES_PASSWORD: ${FILEFLY_DB_PASSWORD}
      POSTGRES_USER: ${FILEFLY_DB_USERNAME}
      POSTGRES_DB: ${FILEFLY_DB_DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - filefly_db_data:/var/lib/postgresql

volumes:
  filefly_db_data: